### ISSUE TITLE
1.13?

### ISSUE THREAD

**Issue by xTreMeDani** [redraskal/GhostScavengerHunt#2]
Hey bro
I have a question, will you update the plugin for version 1.13, will you need some change or will it be so "small" the plugin will not need any change and can be used comfortably?

I await an answer, thanks

**Comment by redraskal** [comment]
The plugin should run on 1.13 without any issues, does it error out?

**Comment by xTreMeDani** [comment]
because the truth is that I have not tried it, it was in case you had to do some update or something xD, thanks for the clarification

**Comment by redraskal** [comment]
Nah, really only plugins using NMS have to upgrade since the spigot update was designed for most plugins to function fine without any modifications. I’ll update the resource page later today.

**Comment by xTreMeDani** [comment]
Ok, thank you very much for the clarification, have a good day :)
