### ISSUE TITLE
Error on Loading - Plugin needs to be reloaded once

### ISSUE THREAD

**Issue by CloudeLecaw** [redraskal/GhostScavengerHunt#4]
```
>.... [22:15:45 WARN]: [GhostScavengerHunt] Could not save messages.yml to plugins/GhostScavengerHunt/messages.yml because messages.yml already exists.
```

```
>....=>.... [22:12:43 INFO]: [GhostScavengerHunt] Disabling GhostScavengerHunt v2.1.0-SNAPSHOT
>.... [22:12:45 INFO]: [GhostScavengerHunt] Enabling GhostScavengerHunt v2.1.0-SNAPSHOT
>.... [22:12:45 WARN]: [GhostScavengerHunt] Could not save messages.yml to plugins/GhostScavengerHunt/messages.yml because messages.yml already exists.
```
On our Server we get this line on start each time
the head plugin does not work before we reloaded it
but on reloading we also get this crazzy meassage about the message.yml

after reloading once the plugin works fine

**Comment by redraskal** [comment]
The warning about the messages.yml is not an issue, it just outputs that after the config files are initially generated. What version of the server and the plugin are you running?

**Comment by CloudeLecaw** [comment]
The 2.1.0 snapshot was your latest version. The server itself runs on papermc 1.16.1 build 90

**Comment by redraskal** [comment]
What does not working mean? The plugin doesn't load and its red on the plugin list or something like clicking skulls doesn't do anything?

**Comment by CloudeLecaw** [comment]
no the plugin seems to load but when someone tries to click on a heads he ahs to find nothing happens if he clicks them

Then after the reloading the plugin works fine and player get the heads counted if they click on it.

next thing maybe interesting: The headsearch is in a seperate world not the regular one (world_ world_nether_world_end) [the world ii created for this is called Eventworld]
maybe it has something to do with the worlds not loaded at the time when the plugin loaded?
this would need some kind of softdpend hoook for  plugins like multiverse core or multiworld, so it can make sure the world allready is laoded. but maybe this kind of softhook allready exists...
when i reload the plugin at the moment at this point all plugins and so also the worldmanager (and therefor the worlds) are loaded.. well just an idea what may could cause this...

The plugin we are using for worldmanagement is multiverse-core

**Comment by redraskal** [comment]
Might have a fix for that.

**Comment by redraskal** [comment]
Let me know if the latest plugin update fixes the issue: https://www.spigotmc.org/resources/ghostscavengerhunt-1-13-1-16-1-support.48523/update?update=348100

**Comment by CloudeLecaw** [comment]
fixed
